// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['text!templates/layouts/main_layout.html'], function(template) {
  var _ref;
  return Forum.Layouts.MainLayout = (function(_super) {
    __extends(MainLayout, _super);

    function MainLayout() {
      _ref = MainLayout.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    MainLayout.prototype.template = _.template(template);

    MainLayout.prototype.regions = {
      head: 'div[role=head]',
      content: 'div[role=content]',
      footer: 'div[role=footer]'
    };

    return MainLayout;

  })(Marionette.Layout);
});
