// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['text!templates/layouts/theme_layout.html'], function(template) {
  var _ref;
  return Forum.Layouts.ThemeLayout = (function(_super) {
    __extends(ThemeLayout, _super);

    function ThemeLayout() {
      _ref = ThemeLayout.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ThemeLayout.prototype.template = _.template(template);

    ThemeLayout.prototype.regions = {
      themeHead: 'div[role=theme-head]',
      messages: 'div[role=theme-messages]',
      replayForm: 'div[role=message-form]'
    };

    return ThemeLayout;

  })(Marionette.Layout);
});
