// Generated by CoffeeScript 1.6.3
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Forum.Views.Themes.EmptyView = (function(_super) {
  __extends(EmptyView, _super);

  function EmptyView() {
    _ref = EmptyView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  EmptyView.prototype.template = _.template("<h5>No themes, yet</h5>");

  return EmptyView;

})(Backbone.Marionette.ItemView);
