// Generated by CoffeeScript 1.6.3
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Forum.Views.Themes.IndexView = (function(_super) {
  __extends(IndexView, _super);

  function IndexView() {
    _ref = IndexView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  IndexView.prototype.itemView = Forum.Views.Themes.ItemView;

  IndexView.prototype.emptyView = Forum.Views.Themes.EmptyView;

  IndexView.prototype.tagName = 'table';

  IndexView.prototype.className = 'table table-hover';

  return IndexView;

})(Backbone.Marionette.CollectionView);
