// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['text!templates/themes/show.html'], function(template) {
  var _ref;
  return Forum.Views.Themes.ShowView = (function(_super) {
    __extends(ShowView, _super);

    function ShowView() {
      _ref = ShowView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ShowView.prototype.template = _.template(template);

    return ShowView;

  })(Backbone.Marionette.ItemView);
});
