// Generated by CoffeeScript 1.6.3
var _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Forum.Models.Theme = (function(_super) {
  __extends(Theme, _super);

  function Theme() {
    _ref = Theme.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return Theme;

})(Backbone.Model);

Forum.Collections.ThemesCollection = (function(_super) {
  __extends(ThemesCollection, _super);

  function ThemesCollection() {
    _ref1 = ThemesCollection.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  ThemesCollection.prototype.model = Forum.Models.Theme;

  ThemesCollection.prototype.localStorage = new Backbone.LocalStorage("ThemesCollection");

  return ThemesCollection;

})(Backbone.Collection);
