// Generated by CoffeeScript 1.6.3
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Forum.Router = (function(_super) {
  __extends(Router, _super);

  function Router() {
    _ref = Router.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Router.prototype.initialize = function() {
    return this.controller = new Forum.Controllers.ThemesController();
  };

  Router.prototype.appRoutes = {
    '': 'index',
    'page-:page': 'index',
    'themes/:id': 'theme'
  };

  return Router;

})(Backbone.Marionette.AppRouter);
