// Generated by CoffeeScript 1.6.3
var _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Forum.Models.Message = (function(_super) {
  __extends(Message, _super);

  function Message() {
    _ref = Message.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return Message;

})(Backbone.Model);

Forum.Collections.MessagesCollection = (function(_super) {
  __extends(MessagesCollection, _super);

  function MessagesCollection() {
    _ref1 = MessagesCollection.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  MessagesCollection.prototype.model = Forum.Models.Message;

  MessagesCollection.prototype.localStorage = new Backbone.LocalStorage("MessagesCollection");

  MessagesCollection.prototype.fetchByTheme = function(themeId, successCb) {
    var _this = this;
    return this.fetch({
      success: function() {
        return successCb(new Forum.Collections.MessagesCollection(_this.where({
          themeId: themeId
        })));
      }
    });
  };

  return MessagesCollection;

})(Backbone.Collection);
